version: 2.1
orbs:
  flutter: circleci/flutter@1.1.0
jobs:
  install:
    docker:
      - image: 'cirrusci/flutter'
    steps:
      - run: "apt install -y libsqlite3-dev"
workflows:
  test:
    jobs:
      - install
      - flutter/unit_test:
          version: 3.0.1
          requires: 
            - install
